apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    app: app-python
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}